root_data_dir: /srv/data
data_version: '06'
galleries_pages:
  - https://www.galleriesnow.net/exhibitions/london
  - https://www.galleriesnow.net/exhibitions/berlin
  - https://www.galleriesnow.net/exhibitions/paris
service_data_dir_name: 'service_data' 